/*import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/index.css"
import { ThemeProvider } from "@/components/ui/theme-provider";
import ChatSupport from "@/components/ui/chat-support";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-muted/30`}>
        <ThemeProvider attribute="class" defaultTheme="system">
          <main className="min-h-screen">
            {children}
          </main>
          <ChatSupport />
        </ThemeProvider>
      </body>
    </html>
  );
}*/